[2024-05-09T23:16:23.150+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:16:20.766286+00:00 [queued]>
[2024-05-09T23:16:23.162+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:16:20.766286+00:00 [queued]>
[2024-05-09T23:16:23.162+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-09T23:16:23.180+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_minio> on 2024-05-09 23:16:20.766286+00:00
[2024-05-09T23:16:23.187+0000] {standard_task_runner.py:57} INFO - Started process 1381 to run task
[2024-05-09T23:16:23.193+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pyspark_dag', 'pyspark_minio', 'manual__2024-05-09T23:16:20.766286+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmp92_oljjh']
[2024-05-09T23:16:23.195+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask pyspark_minio
[2024-05-09T23:16:23.247+0000] {task_command.py:416} INFO - Running <TaskInstance: pyspark_dag.pyspark_minio manual__2024-05-09T23:16:20.766286+00:00 [running]> on host b2123672b907
[2024-05-09T23:16:23.350+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_dag' AIRFLOW_CTX_TASK_ID='pyspark_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T23:16:20.766286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T23:16:20.766286+00:00'
[2024-05-09T23:16:23.380+0000] {docker.py:343} INFO - Starting docker container from image wba-demo/spark:latest
[2024-05-09T23:16:23.384+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-05-09T23:16:23.894+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m23:16:23.89 [0m[38;5;2mINFO [0m ==>
[2024-05-09T23:16:23.896+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m23:16:23.89 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-05-09T23:16:23.897+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m23:16:23.89 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-05-09T23:16:23.899+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m23:16:23.89 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-05-09T23:16:23.900+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m23:16:23.90 [0m[38;5;2mINFO [0m ==>
[2024-05-09T23:16:23.909+0000] {docker.py:413} INFO - 
[2024-05-09T23:16:28.162+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-05-09T23:16:28.309+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2024-05-09T23:16:28.318+0000] {docker.py:413} INFO - io.delta#delta-core_2.12 added as a dependency
[2024-05-09T23:16:28.318+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-05-09T23:16:28.321+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ccd92aaf-0f06-4f31-ad47-b905920620b0;1.0
[2024-05-09T23:16:28.321+0000] {docker.py:413} INFO - confs: [default]
[2024-05-09T23:16:31.080+0000] {docker.py:413} INFO - found io.delta#delta-core_2.12;2.4.0 in central
[2024-05-09T23:16:31.753+0000] {docker.py:413} INFO - found io.delta#delta-storage;2.4.0 in central
[2024-05-09T23:16:36.313+0000] {docker.py:413} INFO - found org.antlr#antlr4-runtime;4.9.3 in central
[2024-05-09T23:16:40.749+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-aws;3.3.6 in central
[2024-05-09T23:16:43.072+0000] {docker.py:413} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.367 in central
[2024-05-09T23:16:46.751+0000] {docker.py:413} INFO - found org.wildfly.openssl#wildfly-openssl;1.1.3.Final in central
[2024-05-09T23:16:46.971+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar ...
[2024-05-09T23:16:48.534+0000] {docker.py:413} INFO - [SUCCESSFUL ] io.delta#delta-core_2.12;2.4.0!delta-core_2.12.jar (1751ms)
[2024-05-09T23:16:48.727+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar ...
[2024-05-09T23:16:49.060+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-aws;3.3.6!hadoop-aws.jar (520ms)
[2024-05-09T23:16:49.250+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-storage/2.4.0/delta-storage-2.4.0.jar ...
[2024-05-09T23:16:49.448+0000] {docker.py:413} INFO - [SUCCESSFUL ] io.delta#delta-storage;2.4.0!delta-storage.jar (387ms)
[2024-05-09T23:16:49.643+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
[2024-05-09T23:16:49.890+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (435ms)
[2024-05-09T23:16:50.085+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.367/aws-java-sdk-bundle-1.12.367.jar ...
[2024-05-09T23:18:10.606+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.amazonaws#aws-java-sdk-bundle;1.12.367!aws-java-sdk-bundle.jar (80714ms)
[2024-05-09T23:18:10.800+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.1.3.Final/wildfly-openssl-1.1.3.Final.jar ...
[2024-05-09T23:18:11.089+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.wildfly.openssl#wildfly-openssl;1.1.3.Final!wildfly-openssl.jar (479ms)
[2024-05-09T23:18:11.092+0000] {docker.py:413} INFO - :: resolution report :: resolve 18462ms :: artifacts dl 84308ms
[2024-05-09T23:18:11.094+0000] {docker.py:413} INFO - :: modules in use:
[2024-05-09T23:18:11.095+0000] {docker.py:413} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.367 from central in [default]
	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2024-05-09T23:18:11.096+0000] {docker.py:413} INFO - io.delta#delta-storage;2.4.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2024-05-09T23:18:11.097+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-aws;3.3.6 from central in [default]
	org.wildfly.openssl#wildfly-openssl;1.1.3.Final from central in [default]
[2024-05-09T23:18:11.098+0000] {docker.py:413} INFO - ---------------------------------------------------------------------
[2024-05-09T23:18:11.100+0000] {docker.py:413} INFO - |                  |            modules            ||   artifacts   |
[2024-05-09T23:18:11.101+0000] {docker.py:413} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2024-05-09T23:18:11.102+0000] {docker.py:413} INFO - |      default     |   6   |   6   |   6   |   0   ||   6   |   6   |
	---------------------------------------------------------------------
[2024-05-09T23:18:11.110+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-ccd92aaf-0f06-4f31-ad47-b905920620b0
[2024-05-09T23:18:11.112+0000] {docker.py:413} INFO - confs: [default]
[2024-05-09T23:18:11.406+0000] {docker.py:413} INFO - 6 artifacts copied, 0 already retrieved (309034kB/295ms)
[2024-05-09T23:18:11.545+0000] {docker.py:413} INFO - 24/05/09 23:18:11 ERROR Configuration: error parsing conf file:/opt/bitnami/spark/conf/hive-site.xml
org.apache.hadoop.shaded.com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </configuration>; expected </property>.
 at [row,col,system-id]: [41,15,"file:/opt/bitnami/spark/conf/hive-site.xml"]
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:634)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:504)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:488)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3352)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3279)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2900)
	at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1121)
	at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3396)
	at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3182)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3075)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3041)
	at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2914)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2896)
	at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2959)
	at org.apache.spark.deploy.SparkHadoopUtil$.hiveConfKeys$lzycompute(SparkHadoopUtil.scala:547)
	at org.apache.spark.deploy.SparkHadoopUtil$.hiveConfKeys(SparkHadoopUtil.scala:542)
	at org.apache.spark.deploy.SparkHadoopUtil$.appendHiveConfigs(SparkHadoopUtil.scala:554)
	at org.apache.spark.deploy.SparkHadoopUtil$.org$apache$spark$deploy$SparkHadoopUtil$$appendS3AndSparkHadoopHiveConfigurations(SparkHadoopUtil.scala:497)
	at org.apache.spark.deploy.SparkHadoopUtil$.newConfiguration(SparkHadoopUtil.scala:483)
	at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$2(SparkSubmit.scala:369)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:369)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-05-09T23:18:11.551+0000] {docker.py:413} INFO - Exception in thread "main"
[2024-05-09T23:18:11.551+0000] {docker.py:413} INFO - java.lang.RuntimeException: org.apache.hadoop.shaded.com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </configuration>; expected </property>.
 at [row,col,system-id]: [41,15,"file:/opt/bitnami/spark/conf/hive-site.xml"]
[2024-05-09T23:18:11.552+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3092)
[2024-05-09T23:18:11.553+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:3041)
	at org.apache.hadoop.conf.Configuration.loadProps(Configuration.java:2914)
[2024-05-09T23:18:11.553+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2896)
[2024-05-09T23:18:11.554+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2959)
[2024-05-09T23:18:11.555+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkHadoopUtil$.hiveConfKeys$lzycompute(SparkHadoopUtil.scala:547)
[2024-05-09T23:18:11.555+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkHadoopUtil$.hiveConfKeys(SparkHadoopUtil.scala:542)
[2024-05-09T23:18:11.555+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkHadoopUtil$.appendHiveConfigs(SparkHadoopUtil.scala:554)
[2024-05-09T23:18:11.556+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkHadoopUtil$.org$apache$spark$deploy$SparkHadoopUtil$$appendS3AndSparkHadoopHiveConfigurations(SparkHadoopUtil.scala:497)
	at org.apache.spark.deploy.SparkHadoopUtil$.newConfiguration(SparkHadoopUtil.scala:483)
[2024-05-09T23:18:11.557+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$2(SparkSubmit.scala:369)
[2024-05-09T23:18:11.557+0000] {docker.py:413} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-05-09T23:18:11.558+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:369)
[2024-05-09T23:18:11.558+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
[2024-05-09T23:18:11.559+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
[2024-05-09T23:18:11.559+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
[2024-05-09T23:18:11.560+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-05-09T23:18:11.560+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2024-05-09T23:18:11.561+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2024-05-09T23:18:11.562+0000] {docker.py:413} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-05-09T23:18:11.562+0000] {docker.py:413} INFO - Caused by: org.apache.hadoop.shaded.com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </configuration>; expected </property>.
 at [row,col,system-id]: [41,15,"file:/opt/bitnami/spark/conf/hive-site.xml"]
[2024-05-09T23:18:11.563+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:634)
[2024-05-09T23:18:11.563+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:504)
[2024-05-09T23:18:11.564+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:488)
[2024-05-09T23:18:11.564+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3352)
[2024-05-09T23:18:11.565+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3279)
[2024-05-09T23:18:11.566+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2900)
[2024-05-09T23:18:11.567+0000] {docker.py:413} INFO - at org.apache.hadoop.shaded.com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1121)
[2024-05-09T23:18:11.567+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3396)
[2024-05-09T23:18:11.567+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3182)
[2024-05-09T23:18:11.568+0000] {docker.py:413} INFO - at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:3075)
[2024-05-09T23:18:11.568+0000] {docker.py:413} INFO - ... 19 more
[2024-05-09T23:18:12.303+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpmygpilyz")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-05-09T23:18:12.308+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_dag, task_id=pyspark_minio, execution_date=20240509T231620, start_date=20240509T231623, end_date=20240509T231812
[2024-05-09T23:18:12.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task pyspark_minio (Docker container failed: {'StatusCode': 1}; 1381)
[2024-05-09T23:18:12.337+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-09T23:18:12.351+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
